model_types:
    - individualized
    - generalized
models:
    - random_forest
    - xgboost
    - svm
    - knn
    - naive_bayes
    - logistic_regression
    - neural_network
datasets:
    - features_video_right.csv
