engagement:
  model_types:
    - individualized
    - generalized
  models:
    - random_forest
    - xgboost
    - svm
    - knn
    - naive_bayes
    - logistic_regression
  dataset: migrave_all.csv
  labels: [1,2,3,4]