model_types:
    - generalized
models:
    - random_forest
    - xgboost
    - svm
    - knn
    - naive_bayes
    - logistic_regression
    - neural_network
    - recurrent_neural_network
    - hmm
    - crf
modalities:
    - video
    - game
datasets:
    - features_video_right.csv
minority_weight_factor: 1
label_issue_file: xgboost_cross_validation_issues.csv
exclude_feature_regex: ^op.*
experiment_name: clean_lab_exclude_issues_exclude_op