model_types:
    - generalized
    - individualized
models:
    - random_forest
    - xgboost
    - svm
    - knn
    - naive_bayes
    - logistic_regression
    - neural_network
    - recurrent_neural_network
    - hmm
    - crf
modalities:
    - video
    - game
datasets:
    - features_video_color.csv
minority_weight_factor: 1
label_issue_file:
exclude_feature_regex: ^op.*|^of_ts_success.*|^ros_skill.*|^ros_mistakes.*|ros_games_session|ros_ts_game_start|^ros_diff.*|ros_aptitude.*|^of_success_.*
exclude_samples_regex: ^of_success_features.*
experiment_name: experiment_name